### ISSUE TITLE
What is differebce between this and  version from "Zathki"?

### ISSUE THREAD

**Issue by Dani3I** [mmatyas/supermariowar-android#2]
If you search for smw for android the first result that is showed to me is: https://github.com/Zathki/supermariowar-android
It seems that last commit on Zathki repo is older than last commit here. Do you know what is Zathki version?

**Comment by mmatyas** [comment]
Hi! This repo contains the tools to create an Android project from the game's source code. The repo you linked seems to be an already set up Android project, with a custom, prebuilt binary of the game (version unknown), a touch screen UI, and a data file downloader.

At the moment, due to technical issues, there's no official Android release of the game, but if there will be, most likely this repo will be used to build it.

**Comment by Dani3I** [comment]
Thank you for helpful explanation. Should I close the issue?

**Comment by mmatyas** [comment]
We can close this, yes.
